### ISSUE TITLE
Complete internals for multiprocess physics kernels

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#125]
This demo app is an opportunity to sketch out the physics and stepping kernels, before focusing on the "big picture" app described in #28 . I'd like to have multiple materials, but due to time constraints I this app can potentially be made a little more foolproof by skipping the secondary/track initialization code and vecgeom integration, perhaps using a simple mock geometry that divides the universe by the plane `x=0` or something (material ID 0 above the plane, 1 below).

Those simplifications aside, there are a few outstanding pieces in the physics that need to be implemented (function names refer to src/physics/base/PhysicsStepUtils.hh):
- [x] Physics array construction from host data (ValueGridBuilder) #128
- [x] Mapping ProcessId -> {energy grid, ModelId} for each particle type #143
- [x] Assembling all the different data structures of the physics interface #141
- [x] `calc_tabulated_physics_step` (not done: on-the-fly processes and perhaps range calculation) #154
- [x] `calc_energy_loss` (not done: "long step" energy loss limiter #160 
- [x] `select_model` (not done) @pcanal

**Comment by sethrj** [comment]
Physics array construction was implemented in #128 .

**Comment by sethrj** [comment]
See https://github.com/celeritas-project/celeritas/wiki/Stepping-algorithm-and-physics-management for more description on what I mean by these guys.
- "Along step kernel" is collaborating -- everyone loses energy
- "Post step kernel" is competing -- if the physics distance is reached, 

From today's discussion, a rough sketch of what the post-step kernel might look like:
```cuda
__global__ post_step(...)
{
    // Actual distance may be less than remaining interaction: it could be
    // limited by the along-step length *or* we could have hit a geometry
    // boundary
    physics.interaction_mfp() -= actual_distance * total_xs;

    // ModelId model = select_model(particle, physics, rng);
    ModelId model; // Default to no model if still remaining mfp
    if (physics.interaction_mfp() <= 0)
    {
        // We're at or past the interaction point: sample the process and
        // determine the corresponding model.
        model = sample_process_and_select_model(...);
        CELER_ASSERT(model);
    }
}
```

**Comment by sethrj** [comment]
Completed the first fully working implementation of the Physics class and data access in #144 .

**Comment by sethrj** [comment]
Status update:
- I think  @vrpascuzzi said he'd hand the energy loss step to me (or someone else willing)?
- @pcanal I think with the `ModelFinder` I put in, `select_model` shouldn't be too bad. Have you made any progress on that?

**Comment by amandalund** [comment]
I can take a shot at the energy loss step if you want.

**Comment by sethrj** [comment]
I already dug kinda deep into the energy loss data (e.g. how `theInverseRangeTable` in `G4VEnergyLossProcess::ScaledKinEnergyForLoss` is just the same data as the `RangeTable` but bisected by value not index) so I don't think this would be best for you...

It might be good for us to get a small group together to tackle the energy loss calculation. (Code posse?)I recall leaving it for later because the Geant4 implementation of the correction term was kinda funky and I thought it would be good to have someone with more experience with charged particle transport/geant4 than I have. Maybe Thursday physics?

**Comment by vrpascuzzi** [comment]
@sethrj,
> * I think  @vrpascuzzi said he'd hand the energy loss step to me (or someone else willing)?

It was either you or Soon. Because I've been tied up with other things the past couple weeks, I opted for another interactor/model instead so as to not hold this up.

**Comment by amandalund** [comment]
ahh gotcha, yeah that sounds good.

**Comment by sethrj** [comment]
Thanks folks. Soon's still working on magnetic field; that'll take a bit more work on his end to get ready.
