### ISSUE TITLE
Minimal muon EM physics processes

### ISSUE THREAD

**Issue by tmdelellis** [celeritas-project/celeritas#1272]
The muon beam is the source term itself and we must likely will not have to plan for any previous part of the beamline. In this scenario, to simulate different muon beam profiles interacting with a d-t mixture, the physics list includes standard EM muon physics, plus decay. The `process: models` list is:

  - [x] `G4MuIonisation`
    - [x] `G4ICRU73QOModel` mu- 0—200 keV (#1309 )
    - [x] `G4BraggModel` mu+ 0—200 keV (#1309 )
    - [x] `G4BetheBlochModel` mu- and mu+ 200 keV-1 GeV (Geant4 versions prior to 11.1.0) (#1425 )
    - [x] `G4MuBetheBlochModel` mu- and mu+ above 200 keV (#1291 )
  - [ ] `G4MuMultipleScattering`
    - [x] Initially by supporting muons in Urban MSC (#1574, #1581  )
    - [ ] Ultimately by adding`G4WentzelVIModel`
  - [x] `G4CoulombScattering`:  `G4eCoulombScattering` (with additions to support muons #1574 )
  - [x] `G4MuPairProduction`: `G4MuPairProductionModel` (#1518 )
  - [x] `G4MuBremsstrahlung`: `G4MuBremsstrahlungModel` (#257 #1319 #1320 #1509)

Verification problems
- [ ] TBD
