### ISSUE TITLE
Initial optical photon stepping loop

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#1374]
Splitting from #886

- [x] Offloading of cerenkov/scintillation from main stepping loop (#1184, #1173, #1153 )
- [x] Optical material data
- [x] Optical core state, params, and actions #1386 
- [x] Creating optical primaries from offload distributions #1399, #1414
- [x] Initialization of optical tracks from optical photon primaries #1441 
- [x] Tracking across boundaries #1417 
- [x] Along-step: find distance, update time
- [ ] "Calorimeter"-like output when tracks hit SD regions
- [ ] Compare step distributions with Geant4

Additional validation TBD
