### ISSUE TITLE
XLZD integration

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#1401]
This is the primary tracking issue for integrating Celeritas with the simulation workflow for the next-generation [XLZD experiment](https://xlzd.org) under development. The primary Celeritas contact points are the "assignees" to the right.

XLZD is being designed through 2030. A grand vision is to export directly from CAD rather than using CSG.

# Core capabilities

- [ ] Optical photon physics: #886
- [ ] ORANGE for platform portability: #1167
- [ ] Eventually: tesselated geometry: #1400

**Comment by seriksen** [comment]
One of the XLZD simulation options can be found here: [https://gitlab.com/XLZD-UK/xlzd-sandbox](https://gitlab.com/XLZD-UK/xlzd-sandbox)

Currently the geometry is constructed in G4 using either `G4MultiUnion` or `G4DisplacedSolid` and `G4UnionSolid`. The latter should be celeritas compatible.
