### ISSUE TITLE
Add muon-catalyzed fusion physics

### ISSUE THREAD

**Issue by stognini** [celeritas-project/celeritas#1508]
# Physical processes

## Necessary for a proof-of-principle

- Muonic atom capture (G4/NK)
  - Formation of $d\_\mu$ and $t\_\mu$
- Muonic molecule formation (G4/NK)
  - Formation of $(dd)\_\mu$ , $(dt)\_\mu$ , or $(tt)\_\mu$
- MuCF (NK)
  - Fusion of of $(dd)\_\mu$ , $(dt)\_\mu$ , and $(tt)\_\mu$
- Muon decay (G4)
- Muon basic EM physics
- Neutron, alpha, proton, $^3\text{He}$, and $^4\text{H}$ transport

## Good to have

- Muonic atom decay (G4)
- Isotopic transfer (NK)
  - Muon tends to be transferred to higher Z atoms
- Muon atom stripping (NK)
- Alpha deexcitation cascade
- Spin flip
- Muon, alpha, neutron (G4)
  - Energy-loss
  - Ionization
  - Scattering

# TODO

- [x] Verify changes in the [NK-Labs Geant4](https://github.com/stognini/nklabs-geant4)
  - [x] Test changes on Geant4 v11+
- [x] Add NK Labs physics list to `utils/celer-geant`
- [ ] Add muon decay to Celeritas' stepper ([PR 1456](https://github.com/celeritas-project/celeritas/pull/1456) and [PR 1991](https://github.com/celeritas-project/celeritas/pull/1991))
- Add muCF in Celeritas
  - [x] Expand `SetupOptions` to include muCF
  - [x] Expand `inp::` data to include muCF physics ([PR 2125](https://github.com/celeritas-project/celeritas/pull/2125))
  - [x] Expand `GeantImporter` to initialize muCF physics ([PR 2125](https://github.com/celeritas-project/celeritas/pull/2125)) 
  - [ ] Expand `ProcessBuilder` to include muCF process
  - [ ] Add neutron, even if it does not have physics attached to it
  - [ ] Address muonic atom and its decay in Celeritas
  - [ ] Add at-rest competition between processes
  - [ ] Add process/model class
    - [x] Draft full skeleton as an at-rest execution and define host/device data struct ([PR 2211](https://github.com/celeritas-project/celeritas/pull/2211))
    - [ ] Add tabulated data in `inp::` and construct device data ([PR 2240](https://github.com/celeritas-project/celeritas/pull/2240))
    - MuCF interactors
      - [x] dd ([PR 2236](https://github.com/celeritas-project/celeritas/pull/2236))
      - [x] dt ([PR 2211](https://github.com/celeritas-project/celeritas/pull/2211))
      - [ ] tt 
    - [x] Atom + spin selectors ([PR 2216](https://github.com/celeritas-project/celeritas/pull/2216))
    - [ ] Molecule + spin selectors
    - Second order effects
      - [ ] Spin flip helper
      - [ ] Atom transfer helper
  - [ ] Verify with `TrackingManager` and `UserAction` integrations
- [ ] Validate Geant4 vs. Celeritas muon EM and fusion physics via `CELER_DISABLE` toggle

**Comment by stognini** [comment]
# Physics cycle

- Physical interaction times
```mermaid
flowchart LR
mu[Muon] --"10^{-12} - 10^{-13} s"--> muatom["Atom formation"]
muatom --"10^{-8} - 10^{-10} s"--> molecule["Molecule formation"]
molecule --"10^{-12} s"--> Fusion
```
- Cycle times (atom formation to fusion) heavily depend on material temperature [[PhysRevLett.51.1757](https://doi.org/10.1103/PhysRevLett.51.1757)]
  - Ref. above states the $(dt)\_\mu$ molecular formation $\lambda_{dt\mu}$ being 3 to 7 $\times 10^{-8}$ s, but theoretical limit is at $10^{-10}$ s [[10.1016/0920-3796(89)90023-9](https://ui.adsabs.harvard.edu/abs/1989FusED..11..255P/abstract)] 
- The muon can decay at any time
- Fusion channels:
  - $(dd)_\mu$
    - $\longrightarrow ^3\text{He} + \mu + n + 3.27 \ \text{MeV}$
    - $\longrightarrow (^3\text{He})_\mu + n + 3.27 \ \text{MeV}$
    - $\longrightarrow t + \mu + p + 4.03 \ \text{MeV}$
    - $\longrightarrow (t)_\mu + p + 4.03 \ \text{MeV}$
  - $(dt)_\mu$
    - $\longrightarrow \alpha + \mu + n + 17.6 \ \text{MeV}$
    - $\longrightarrow (\alpha)_\mu + n + 17.6 \ \text{MeV}$
  - $(tt)_\mu$
    - $\longrightarrow \alpha + \mu + 2n + 11.33 \ \text{MeV}$
    - $\longrightarrow (\alpha)_\mu + 2n + 11.33 \ \text{MeV}$
    - There is also the resonant channel
      $^5\text{He} + \mu + n \longrightarrow t + \mu + 2n + 8.7 \ \text{MeV}$
      - Probably below second order effects in terms of relevance

- Experimental data is broken down into grid tables with temperature (x) vs. rate (y). This applies to mean cycle times, mean atom transfers, and mean atom spin flip.
- Cycle time depends on spin as well. Theoretically, there are many possible states (see table), but only a few are reactive, i.e. have the correct rotational and nuclear-spin symmetry to tunnel through the Coulomb barrier. All these project onto $J = 1$.
  - States not containing $J = 1$ have fusion rates orders of magnitude lower
  - $(dt)_\mu$ is the dominant channel by far (> 80%).

  | Molecule   | Nuclei   | $I_N$    | $F = I_N \pm 1/2$ | Reactive states (F) |
  | ---------- | -------- | -------- | ----------------- | ------------------- |
  | $(dd)_\mu$ | 1, 1     | 0, 1, 2  | 1/2, 3/2, 5/2     | 1/2, 3/2            |
  | $(dt)_\mu$ | 1, 1/2   | 1/2, 3/2 | 0, 1, 2           | 0, 1                |
  | $(tt)_\mu$ | 1/2, 1/2 | 0, 1     | 1/2, 3/2          | 1/2                 |

> **___Only the reactive states should be implemented___**


# Geant4 implementation (Acceleron)

The `MuonCatalyzedFusion::AtRestDotIt` sequence is

```mermaid
---
title: DD
---
flowchart LR
a["calculate cycle time"] --> b["sample sticking"] --> d["sample secondaries"]
d --> he3["He-3"]
d --> h["H-3"]
he3 --> he3s["(He-3)mu + n"]
he3 --> he3ns["He-3 + mu + n"]
h -. not implemented .-> hs["(H-3)mu + p"]
h --> hns["H-3 + mu + p"]
```
```mermaid
---
title: DT
---
flowchart LR
a["calculate cycle time"] --> b["sample sticking"] --> d["sample secondaries"]
d --> e
d --> f
e["(alpha)mu + n"]
f["alpha + mu + n"]
```
```mermaid
---
title: TT
---
flowchart LR
a["calculate cycle time"] --> b["sample sticking"] --> d["sample secondaries"]
d --> e
d --> f
e["(alpha)mu + n + n"]
f["alpha + mu + n + n"]
```

## Transport loop

```mermaid
flowchart LR
step["stepping loop"]
competition["at-rest process selection"]
capture["muonic atom capture
        (spin is selected)"]
fusion["DD/DT/TT fusion process
       (molecule never exists in the stepping loop)"]

step-->competition
competition --> capture & fusion
capture --muonic atom inserted in step--> competition
fusion --secondaries inserted in stepping loop --> step
```
The muonic molecule never exists in the stepping loop. The fusion process is selected based on the muonic atom and the material. E.g. if it is a $(d)\_\mu$ and the amount of tritium in the material is `tritium_num_dens < std::numeric_limits<double>::epsilon()`, then for the $(dt)\_\mu$ process `mean_cycle_time = std::numeric_limits<double>::infinity()`


# Celeritas implementation

- In Celeritas, one large `Executor` does all the work
- At rest process:
  - Form muonic atom
  - May execute atom spin flip or atom transfer
  - Calculate mean cycle time (time it takes from atom formation to fusion)
  - Form muonic molecule and select its spin
  - Confirm if fusion happens or the if the muon decays before that
  - Select channel and call appropriate `Interactor`

```mermaid
flowchart LR

%% Main flowchart
atom[muonic atom]
molecule[muonic molecule]
spinflip[spin flip]
transfer[isotopic transfer]
cycle[cycle time]

atom --> molecule --> cycle --> dd & dt & tt
atom --> spinflip & transfer --> molecule
molecule -.-> decay

subgraph second[Second order effects]
    spinflip
    transfer
end

subgraph mucf[muCF]
    direction LR

    %% DD fusion
    dd[DD]
    he3[$$^3$$He]
    h[H]
    ddhe3s["(He-3)mu + n"]
    ddhe3ns["He-3 + mu + n"]
    ddhs["(H-3)mu + p"]
    ddhns["H-3 + mu + p"]
    dd --> he3 & h
    he3 --> ddhe3s & ddhe3ns
    h -.not
        implemented.-> ddhs
    h --> ddhns

    %% DT fusion
    dt[DT]
    dts["(alpha)mu + n"]
    dtns["alpha + mu + n"]
    dt --> dts & dtns

    %% TT fusion
    tt[TT]
    tts["(alpha)mu + n + n"]
    ttns["alpha + mu + n + n"]
    tt --> tts & ttns
end

ddhe3s & ddhs & dts & tts --> stripping["Muon stripping"]
```

- Each `Interactor` (one for each: dd, dt, tt) takes as input the selected fusion channel and it simply returns an `Interaction::from_absorption()` and samples the outgoing secondaries.

## Model/Executor class diagram

```mermaid
classDiagram
class DTMixMucfExecutor {
    At-rest muon-catalyzed fusion executor
    Interaction operator()(celeritas::CoreTrackView const& track)
}

DTMixMucfExecutor <-- MuonicAtomSelector
DTMixMucfExecutor <-- MuonicAtomSpinSelector
DTMixMucfExecutor <-- MuonicMoleculeSelector
DTMixMucfExecutor <-- MuonicMoleculeSpinSelector
DTMixMucfExecutor <-- DDMucfInteractor
DTMixMucfExecutor <-- DTMucfInteractor
DTMixMucfExecutor <-- TTMucfInteractor

DDMucfInteractor <-- DDChannelSelector
DTMucfInteractor <-- DTChannelSelector
TTMucfInteractor <-- TTChannelSelector

DTMixMucfModel <-- DTMixMucfExecutor
DTMixMucfModel <-- DTMixMucfData

%%---------------------------------------------------------------------------%%
%% Purpose-specific helper classes
namespace detail {
    class MuonicAtomSelector {
        Muonic atom formation
        DTMixMuonicAtomSelector(...)
        Result operator(Engine& rng)
    }
    class MuonicAtomSpinSelector {
        Atom spin selector
        DTMixMuonicAtomSpinSelector(...)
        Result operator(Engine& rng)
    }
    class MuonicMoleculeSelector {
        Muonic molecule formation
        DTMixMuonicMoleculeSelector(...)
        Result operator(Engine& rng)
    }
    class MuonicMoleculeSpinSelector {
        Molecule spin selector
        DTMixMuonicMoleculeSpinSelector(...)
        Result operator(Engine& rng)
    }
    class DDChannelSelector {
        Select channel for dd fusion
        DDChannelSelector(...)
        Result operator(Engine& rng)
    }
    class DTChannelSelector {
        Select channel for dt fusion
        DTChannelSelector(...)
        Result operator(Engine& rng)
    }
    class TTChannelSelector {
        Select channel for tt fusion
        TTChannelSelector(...)
        Result operator(Engine& rng)
    }
}

%%---------------------------------------------------------------------------%%
%% Return Interaction result
namespace Interaction {
    class DDMucfInteractor {
        Interactor for DD muCF
        DDMucfInteractor(...)
        Result operator(Engine& rng)
    }
    class DTMucfInteractor {
        Interactor for DT muCF
        DTMucfInteractor(...)
        Result operator(Engine& rng)
    }
    class TTMucfInteractor {
        Interactor for TT muCF
        TTMucfInteractor(...)
        Result operator(Engine& rng)
    }
}

%%---------------------------------------------------------------------------%%
%% Process / Model
namespace Model {
    class DTMixMucfModel {
        DT muCF model
        DTMixMuonCatalyzedFusionModel()
        void step(CoreParams const&, CoreState&)
        DTMixMuonCatalyzedFusionData data_
    }
    class DTMixMucfData {
        Static scalars
        Static grid tables
        Material-dependent data
    }
}
```

### Model/Executor host/device data

```mermaid
flowchart LR
subgraph memspace["DTMixMuonCatalyzedFusionData"]
    subgraph static scalars
        scalars["Particle Ids
                 Particle masses"]
    end
    subgraph static tables
        energy["Muon energy CDF"]
    end
    subgraph per-material scalars
        cycle["Cycle times"]
        spinflip["Spin flip times"]
        transfer["Atom transfer times"]
    end
end
```

## MuCF in the stepping loop

```mermaid
flowchart LR
step["stepping loop"]
rest["at-rest process selection"]
executor["MuCF Executor"]
mucf["MuCF Interactor"]
decay["Decay"]

step --> rest --> executor --> mucf
step --> decay
rest --> decay
mucf --secondaries inserted in stepping loop--> step
```
