### ISSUE TITLE
End-of-Q3 code review

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#163]
- [ ] Convert remaining manual allocations to use `Collection`s
  - [x] Livermore data #185 
  - [ ] Atomic relaxation data @amandalund  
  - [x] Stack allocator #169 
  - [x] Vecgeom state data #201 
  - [x] Track initializer #240 
  - [x] RNG states #199 
- [ ] Drop `View` suffix (?) definitely from stack allocator, possibly also from other views
- [ ] Move some files around?
  - [ ] physics/material -> physics/base since there are fewer classes there now
  - [ ] comm and base are awkward -- maybe we should have base/{host,device,hostdevice} or something indicating where the classes are used
  - [x] random/cuda is also a bit awkward all alone #199
- [x] Review physics interactors for duplicate random distributions that can be consolidated
  - [x] `Selector` for the multiple places where we sample an on-the-fly discrete PDF #217
  - [x] `RejectionSampler` for the reverse of a `BernoulliDistribution` and without the division, see https://github.com/celeritas-project/celeritas/pull/209#discussion_r611149489 [LivermorePE, Rayleigh, select_process_and_model, AtomicRelaxation, ElementSelector]
  - [x] `x = xmin * exp(xi * log(xmax / xmin)) = xmin * (xmax / xmin)^xi` from `f(x) = 1/x` (EPlusGG, KleinNishina, SB) #220
- [x] Streamline data organization/file layout between IO and physics
  - [x] Raw imported livermore data lives in IO, livermore params #185 
  - [x] RootImporter returns `ImportFile` #210
  - [x] Particle params has a constructor from `ImportFile` #210
  - [x] ~~Only import (or perhaps export?) particle types that are present in processes being exported~~
- [x] PDG numbers should be their own tiny class, now that OpaqueId is universally an index holding an unsigned int #219
- [x] InteractorHostTest should reset RNG counter with call to `this->rng()` #205
