### ISSUE TITLE
Simulation mega task list

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#18]
The simulation is responsible for choosing which action a particle undergoes. It maintains a count of the accumulated simulation time since the event and the accumulated path length of a track.

Simulation:
- [X] Initialize tracks from events ("event generator")
  - New Primary class
  - New event primaries will have to be injected into arbitrary empty slots (indices) in a vector of tracks
  - Add [HEPMC3](https://gitlab.cern.ch/hepmc/HepMC3) support for constructing "event" (vector of primaries)
- [X] Initialize tracks from secondaries
- [x] Buffer and manage secondaries waiting to be turned into tracks
- [x] Stepping loop

The "simulation" stuff is definitely more nebulous than the other components.

**Comment by sethrj** [comment]
Marking "stepping loop" as completed since we initially had a simple loop in the KN interactor, and I foresee the high-level stepping loop as evolving over our continual set of progression apps.
