### ISSUE TITLE
VecGeom verification for CMS model

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#202]
# Plan for validation

- [ ] Visual inspection of slices with raytrace
- [ ] Visual inspection of (not yet extant) x-ray tool
- [ ] Numeric comparison of volume estimates, loaded through VGDML/ROOT in VecGeom, vs Geant4/G4GDML and possibly even ROOT tracking: simulate reflecting boundaries, uniform isotropic source with isotropic scattering and some absorption fraction

# Tracking 

General VecGeom issues:
- [x] Global initialization not implemented on device #38 [vecgeom!760](https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/760) [vecgeom!768](https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/768) 
- [x] ~~Other initialization crash~~ (@sethrj error, not VecGeom's!) #201

VecGeom issues with CMS:
- [x] Transforms aren't properly applied in VGDML
- [x] Transforms and boolean volumes don't mix [cms images](https://github.com/celeritas-project/celeritas-docs/blob/master/meetings/210302-lima-rasterizer-cms2018.pdf) [vecgeom#565](https://sft.its.cern.ch/jira/browse/VECGEOM-565)
- [x] ROOT units are loaded incorrectly into VecGeom https://github.com/celeritas-project/celeritas/pull/192

VecGeom issues with ATLAS:
- [ ] Hang during load (@vrpascuzzi see below)

**Comment by vrpascuzzi** [comment]
Running `demo-rasterizer` from c4a6493 with an ATLAS GDML input hangs at "Loading from GMDL." (CPU side) The [partial] backtrace we obtained:
```
#0  std::char_traits<char>::length (__s=0x8deace20 "Muon__MDTDriftWall0x3f06d220")
    at /home/leggett/install/gcc/bld_8.4.0/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/char_traits.h:322
#1  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare (
    this=0x89432a00, __s=0x8deace20 "Muon__MDTDriftWall0x3f06d220")
    at /home/leggett/install/gcc/bld_8.4.0/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:1422
#2  0x00007f89c26f8bd8 in vecgeom::cxx::GeoManager::FindLogicalVolume(char const*) ()
   from /home/ddeeb/celeritas/celeritas/build2/src/libceleritas.so
#3  0x00007f89c244223e in vgdml::Middleware::processPhysicalVolume(xercesc_3_2::DOMNode const*) ()
   from /home/ddeeb/celeritas/celeritas/build2/src/libceleritas.so
#4  0x00007f89c2442d5a in vgdml::Middleware::processLogicVolume(xercesc_3_2::DOMNode const*) ()
   from /home/ddeeb/celeritas/celeritas/build2/src/libceleritas.so
#5  0x00007f89c2447726 in vgdml::Middleware::processNode(xercesc_3_2::DOMNode const*) ()
   from /home/ddeeb/celeritas/celeritas/build2/src/libceleritas.so
#6  0x00007f89c244765e in vgdml::Middleware::processNode(xercesc_3_2::DOMNode const*) ()
   from /home/ddeeb/celeritas/celeritas/build2/src/libceleritas.so
#7  0x00007f89c244765e in vgdml::Middleware::processNode(xercesc_3_2::DOMNode const*) ()
   from /home/ddeeb/celeritas/celeritas/build2/src/libceleritas.so
#8  0x00007f89c2437b6f in vgdml::Frontend::Load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, double) ()
   from /home/ddeeb/celeritas/celeritas/build2/src/libceleritas.so
#9  0x00007f89c242a48f in celeritas::GeoParams::GeoParams (this=0x3b944c0, 
    gdml_filename=0x3b8b350 "geometry-ATLAS-R2-2016-01-00-01.gdml")
    at /opt/gcc/8.4.0/include/c++/8.4.0/bits/char_traits.h:287
#10 0x00000000004071ca in __gnu_cxx::new_allocator<celeritas::GeoParams>::construct<celeritas::GeoParams, char const*&> (this=<optimized out>, __p=0x3b944c0) at /opt/gcc/8.4.0/include/c++/8.4.0/new:169
#11 std::allocator_traits<std::allocator<celeritas::GeoParams> >::construct<celeritas::GeoParams, char const*&> (__a=..., __p=0x3b944c0) at /opt/gcc/8.4.0/include/c++/8.4.0/bits/alloc_traits.h:475
#12 std::_Sp_counted_ptr_inplace<celeritas::GeoParams, std::allocator<celeritas::GeoParams>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<char const*&> (__a=..., this=0x3b944b0)
    at /opt/gcc/8.4.0/include/c++/8.4.0/bits/shared_ptr_base.h:545
#13 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<celeritas::GeoParams, std::allocator<celeritas::GeoParams>, char const*&> (__a=..., __p=<synthetic pointer>: <optimized out>, 
    this=<synthetic pointer>) at /opt/gcc/8.4.0/include/c++/8.4.0/bits/shared_ptr_base.h:677
#14 std::__shared_ptr<celeritas::GeoParams, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<celeritas::GeoParams>, char const*&> (__tag=..., this=<synthetic pointer>)
    at /opt/gcc/8.4.0/include/c++/8.4.0/bits/shared_ptr_base.h:1342
#15 std::shared_ptr<celeritas::GeoParams>::shared_ptr<std::allocator<celeritas::GeoParams>, char const*&>
    (__tag=..., this=<synthetic pointer>) at /opt/gcc/8.4.0/include/c++/8.4.0/bits/shared_ptr.h:359
#16 std::allocate_shared<celeritas::GeoParams, std::allocator<celeritas::GeoParams>, char const*&> (
    __a=...) at /opt/gcc/8.4.0/include/c++/8.4.0/bits/shared_ptr.h:706
#17 std::make_shared<celeritas::GeoParams, char const*&> ()
    at /opt/gcc/8.4.0/include/c++/8.4.0/bits/shared_ptr.h:722
#18 demo_rasterizer::run (is=...)
    at /home/ddeeb/celeritas/celeritas/app/demo-rasterizer/demo-rasterizer.cc:47
#19 0x0000000000406b0c in main (argc=<optimized out>, argv=<optimized out>)
    at /home/ddeeb/celeritas/celeritas/app/demo-rasterizer/demo-rasterizer.cc:153
```
Volume "Muon__MDTDriftWall0x3f06d220" appears on line 501594 of the input GDML file.

**Comment by pcanal** [comment]
https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/798 is likely to repair the current vgdml problem seen with the rasterizer.
