### ISSUE TITLE
Add initial diagnostic output to event loop

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#262]
This is a precursor to the more general https://github.com/celeritas-project/celeritas/issues/29 . The most generic way to support interaction with experimental frameworks (or our own internal diagnostics) is to allow callbacks inside every step. This might be through a virtual inheritance hierarchy:
```c++
class Diagnostic
{
  public:
    using DeviceRefs = ModelInteractRefs;
    virtual begin_simulation() {}
    virtual begin_event(EventId, const DeviceRefs&) {}
    virtual begin_step(const DeviceRefs& data) {}
    virtual end_step(const DeviceRefs& data) {}
    virtual end_event(EventId, const DeviceRefs&) {}
    virtual end_simulation() {}
};
```
or perhaps a set of enums and callbacks:
```c++
void add_callback(CallbackTrigger, std::function<void(const DeviceRefs&>);
```

Although we won't need it in the first iteration, for the sake of completeness we'll need to have the code related to secondary initialization to be able to detect when the last secondary produced from given event has been transported (so that analysis code can process the information, e.g. in Acceleritas send the accumulated data back to Geant4).

First pass at diagnostics:
- [x] Number of tracks per step #287 
- [x] Processes and particle types #290 
- [x] Z bin of energy deposition #289 
- [x] Hit creator for acceleritas (@whokion )
