### ISSUE TITLE
Implement portable in-house geometry

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#267]
There are several reasons to support an alternative geometry implementation to VecGeom:
- Exploring performance portability (VecGeom is very closely tied to CUDA)
- Evaluating how the app's overall performance changes when using a less expensive geometry implementation
- Reducing build/CI times

To do this we'll want to:
- Refine geometry propagation/tracking interface. Look at the current use cases for the geometry track view interface, simplify and/or document which functions are part of the "public" interface.
- Possibly template key parts of the code on geometry type, and/or use virtual geometry interfaces for other parts of the CPU code (such as cell labels and high-level kernel launch functionality)

Then we'll add a new surrogate geometry implementation (possibly based on RTK from Shift) for simple geometries with planes and cylinders. Maybe define a new JSON (rather than Teuchos XML) for on-disk representation.

ORANGE:
- [x] Surface intersections (#291)
- [x] Static polymorphism and operator (#306)
- [x] JSON I/O (#307)
- [x] Volumes and initialization (#312)
- [x] Distance-to-boundary (#335)
- [x] Params and TrackView interface (#336)
- [x] Compile-time switching between VecGeom and ORANGE for main codebase (#337)
- [x] Enable previously vecgeom-only tests (#339 )
- [ ] Enable previously vecgeom-only demo (#343)
