### ISSUE TITLE
Support multithreaded Celeritas using single GPU

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#418]
One of the comments during the workshop was that "it's not fair" to compare single-CPU geant vs single-CPU plus single-GPU. What we will probably want to do is enable multithreaded Acceleritas/Celeritas, with each thread corresponding to a Geant4 thread, and all threads sharing both the same `Params` data and executing on a single GPU.

As part of #280 I will be designing the Transporter/Stepper to have shared params data as input and a persistent per-instance set of states. (I.e., each Stepper can independently transport 1M tracks from the same event.) Later we could consider a fancier queuing scheme where the CPU threads push primaries onto a Celeritas thread that keeps the GPU busy, but this is an easy way of keeping all the events separate and minimizing the amount of thread safety concerns.

I think if we add a `StreamId` to the CoreState (and a Streams class to hide the CUDA/HIP/whatever implementation), we could then easily have the different kernels launch on different streams without doing too much code refactoring at all.

https://www.olcf.ornl.gov/wp-content/uploads/2021/05/10-Multithreading-and-CUDA-Concurrency.pdf

- [x] Add StreamId to stepper (#693)
- [x] Initialize RNG with StreamId (#696)
- [x] Use StreamId to access hit collection (#694)
- [ ] Use StreamId to launch kernels on CUDA streams (#777)

**Comment by sethrj** [comment]
We may need to reconsider how to initialize the device on all threads:
https://developer.nvidia.com/blog/cuda-pro-tip-always-set-current-device-avoid-multithreading-bugs/

I know @pcanal pointed this out when we were first working with the `device` singleton. I think for the time being we can constrain our use case to "a single device across all threads"... I guess under the hood the `cudaSetDevice` has a `thread_local` data somewhere? Maybe in the Stepper (which should be thread-local) we just need to reset the device at the beginning?

**Comment by sethrj** [comment]
We may also want a "multithreading" configuration switch, as well as a mutex abstraction that switches between:
- [std::mutex](https://en.cppreference.com/w/cpp/thread/mutex)
- [OpenMP locks](https://www.openmp.org/spec-html/5.0/openmpse31.html)
- No mutexes (presumably faster for serial mode)
- [TBB spin mutex](https://spec.oneapi.io/versions/1.0-rev-2/elements/oneTBB/source/mutual_exclusion/spin_mutex_cls.html)

**Comment by sethrj** [comment]
Possible implementation:
- New classes/data StreamParams and StreamState
- Params is constructed with the maximum number of simultaneous streams (which generally will correspond to threads)
- StreamState just has a `StreamId` that should be unique across all instances of the class on a single MPI process
- For debugging, maybe params keeps track of which stream IDs are in use?
- Either `StepperInput` is given a StreamId, or possibly we atomically increment a shared stream counter?
- RNG `initialize` must take a stream state to construct stream-local initial RNG states
- Classes like `HitProcessor` need to use the stream ID (on the host!) to create and access thread-local data structures, at least until #392 is implemented
