### ISSUE TITLE
Add magnetic field drivers/integrators

### ISSUE THREAD

**Issue by whokion** [celeritas-project/celeritas#49]
Implement magnetic filed integration with a realistic geometry and a non-uniform magnetic field, and test different integrators on GPU.

- [x] Runge-Kutta stepper #173 
- [x] Adaptive step solver #214
- [x] Integrate with geometry/navigator (safety distances, high-level `Propagator`, etc.) #221 
- [x] Nonuniform magnetic field #250

Possible Quantized State System (QSS) implementation?
- [A Stand–Alone Quantized State System Solver for Continuous System Simulation](https://ri.conicet.gov.ar/bitstream/handle/11336/4810/CONICET_Digital_Nro.6447_A.pdf;jsessionid=709EC14AA1A7BAF667CDD777341E4A79?sequence=2)
- [Efficient Discrete-Event Based Particle Tracking Simulation for High Energy Physics](https://arxiv.org/abs/2001.05558)

Possibly implement simpler steppers (e.g. helix) for uniform magnetic fields

**Comment by whokion** [comment]
@sethrj I scratched out classes for the magnetic field integration (FieldPropagator -> ChordFinder -> Driver -> Stepper -> Equation -> Field) with minimal functionalities (without a boundary crossing for now, which can be extended later when navigation is fully working).  One question before moving forward for actual implementation is regarding to how to pass required input for the field integration (i.e., position, direction, kinetic energy and mass (for the momentum three vector), proposed step length, charge) which is combined but parts of information from ParticleTrackView and GeoTrackView.  In fact, the data format that I would like to use is {y(position,momentum), dydx{rhs of equation}, step_length, charge} where y and dydx is an array of dim-6 real_type, which are common input/(output) to most functions of those classes.  Is it worth while to introduce something like FieldTrackView which only contains a set of minimal input for the field integration or just use the ParticleTrackView and  GeoTrackView directly?

**Comment by sethrj** [comment]
Excellent! I really like the `FieldTrackView` idea. What about a `FieldTrackView` that is be a temporary class whose constructor takes a `ParticleTrackView` and `GeoTrackView`? The constructor could do the necessary transformations (e.g. `{energy, direction} -> momentum`) into whatever data format is easiest for the propagation classes, or you could provide accessors that calculate the data on-the-fly. (Either way, I'd use accessors like we do with the other view classes to allow the implementation to change later.)

Does that sound like a good approach?

**Comment by whokion** [comment]
Sounds great!  I will introduce FieldTrackView and will ask your review later.  Thanks.
