### ISSUE TITLE
Basic loop demo integration

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#54]
Propagate through a VecGeom geometry with multiple materials. Include at least one each of continuous and discrete processes. Compare simulation results and timing against Geant4.

Requirements:
- [x] Physics process management (#28)
- [x] Linear propagator interface (#66)
- [x] Material<->volume mapping (#74)
- [x] (Possibly) initialization (#52)

Add the following kernels:
- [X] Pre-step kernel (sample and set remaining mfp if unset, call `calc_tabulated_physics_step`)
- [X] Along-step kernel (determine actual step distance with geometry vs physics; propagate; call `calc_energy_loss`)
- [X] Post-step kernel (decrement distance-to-interaction, call select_model)
- [x] Interactor launches. @sethrj 
  - Get direction from geometry states
  - Template `ModelInterface` on `MemSpace` and overload model `interact` method to work with host pointers
  - Loop over all model IDs and fire off kernels
- [X] Postprocessing secondaries and interaction results
- [x] Initializing tracks from primaries/secondaries @amandalund

Missing pieces:
- [x] Geometry and physics input files
- [x] Source definition (use HepMC3 input) @stognini 
- [x] Missing `Process` classes (Rayleigh?, bremsstrahlung)

**Comment by whokion** [comment]
For a minimal set of EM processes for this multi-processes demo, Compton-Bremsstahlung-Ionization may be a good choice for simulating a self-contained (electron-gamma) cascade, which contains both discrete processes (all of them) and continuous energy loss processes (brem and ioni) with input of either photons or electrons: 1) starting from photons, it will undergo Compton (scattering and electron production) -> electron (energy loss by ionization, delta-ray by ioni and photon production by brem) -> repeat this cycle until both (primary and secondary) photons and secondary electrons reach to energy thresholds of processes,  2) starting with electrons, a similar cycle, but competing (brem+ioni) first followed by Compton and so on.  It is a good demo with a complete simulation cycle for demonstrating performance measurements and basic validations if the total number of steps and tracks are statistically comparable to results from an equivalent Geant4 application.

**Comment by sethrj** [comment]
Rescoping this and calling it done, even though there's still clearly work to be had in the demo loop.
