### ISSUE TITLE
Add multithreaded CPU to single GPU in demo-loop

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#553]
To test out the ability to run multiple Celeritas threads simultaneously on a single CPU we should support an option to run a multithreaded Celeritas with one event per thread all sharing the same CPU. See #418.

- [x] Create a `StreamStateData` that's something like a `StateStore` but is sized based on the number of streams and can dynamically allocate host or device storage as needed. This will be a precursor to a generic capability (#392) for storing arbitrary class-based data on the state. (@sethrj, #722)
- [x] Rename `OutputManager` to `OutputRegistry` and add to `CoreParams` as with the action registry. We should move all the "output creation" helpers from `demo-loop.cc` to  the `CoreParams` constructor. (@sethrj , #710)
- [x] Replace the non-thread-safe diagnostics in the demo-loop (these three can be done in parallel):
  - [x] Define a `SimpleCalorimeter` that subclasses `StepInterface` and `OutputInterface` which will replace the Z energy deposition "diagnostic" in demo-loop. I've already got half a commit so far on this. (@sethrj , #733)
  - [x] Replace `ParticleProcessDiagnostic` with an `ExplicitActionInterface` (and subclass `OutputInterface` as well I think). I think this should be `AlongStep::post`, but I think is currently `ActionOrder::post_post`? Also just store post-discrete action ID so we can get boundary vs range limits, etc. (#740 )
  - [x] Replace `StepDiagnostic` with an `ExplicitActionInterface` as well. (#746)
 - [x] `demo_loop::Transporter` constructor takes a stream ID; add a `#pragma omp parallel` over the thing, divide up the primary vector among the streams

Open questions:
- (How?) do we accumulate diagnostics etc. across all the streams?
- Are there any weird gotchas for embedded parallel blocks? Paul says he implemented a toy that did it and worked.

**Comment by sethrj** [comment]
@paulromano I think you'd be great for doing this task if you have time.
- it won't work initially because of all the thread safety issues
- let's keep it simple and require the diagnostics to be off (they're not thread safe and should be removed in favor of actions/step collector interfaces)
- we'll probably need to work in tandem with #418

**Comment by paulromano** [comment]
Sure thing -- will start working on this!
