### ISSUE TITLE
Extend celer-g4 for detailed Geant4/Celeritas comparisons

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#850]
The goal here is to allow us to do fully apples-to-apples comparisons between Geant4 and Celeritas for CMS.

Core celeritas enhancements:
- [x] Export HepMC3/event file with incoming secondaries (use single file plus mutex) (@sethrj , #854)
- [x] Add a Geant4 magnetic field subclass that can *wrap* a Celeritas field (@whokion, #874)

celer-g4 app enhancements:
- [x] Add none/uniform/RZ magnetic field map option to `DetectorConstruction::ConstructSDandField`
- [x] Add `CELER_DISABLE` option to run geant4-only mode (#860 )
- [x] Add track step counter via `G4UserSteppingAction` (@amandalund #862 )
- [x] ~~(possibly?) Add RootStepWriter to  `G4UserSteppingAction`~~

See also #670 for replacing the validation app.

**Comment by sethrj** [comment]
I think 
> Add stepping counter (track energy vs number of substeps) for magnetic field (need @whokion help)

isn't realistic to add to the main code (likely too expensive as a runtime diagnostic) but it would be a good thing to hack in on a branch?
